### ISSUE TITLE
createEmployeeRecords

### ISSUE THREAD

**Issue by PeteHanner** [learn-co-curriculum/js-advanced-functions-context-lab#3]
Test file calls the function `createEmployeeRecords`, which is not mentioned in the readme and causes the tests to fail. I believe this should be `createEmployees`; I just duplicated that function I had already written and renamed it `createEmployeeRecords`, which cause the failing tests to pass.

**Comment by sgharms** [comment]
Seems I may have gotten my copy and pastes between this readme https://github.com/learn-co-curriculum/js-advanced-functions-introduction-to-context-lab/issues/5 and this lab bungled. Willfix.
