### ISSUE TITLE
Incorrect camel casing?

### ISSUE THREAD

**Issue by nbaugh1** [learn-co-curriculum/js-advanced-functions-context-lab#6]
Should the function be named `findEmployeeByFirstName` rather than `findEmployeebyFristName` as it is currently required in the tests?

**Comment by sgharms** [comment]
@nbaugh1 I think most developers find both pretty easy to read. Typographical conventions aren't like penal codes so it's probably not worth getting _too_ hung up about. But consistency is certainly a good thing, so I'll update.

**Comment by sgharms** [comment]
Fixed in 4e442f0
